default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PGUSER"] || "postgres" %>
  password: <%= ENV["PGPASSWORD"] || "" %>
  host: <%= ENV["PGHOST"] || "localhost" %>

development:
  <<: *default
  database: budgie
  url: <%= "postgresql://#{ENV['PGUSER'] || 'postgres'}:#{ENV['PGPASSWORD']}@#{ENV['PGHOST'] || 'localhost'}/budgie" %>

test:
  <<: *default
  database: budgie_test
  url: <%= "postgresql://#{ENV['PGUSER'] || 'postgres'}:#{ENV['PGPASSWORD']}@#{ENV['PGHOST'] || 'localhost'}/budgie_test" %>

production:
  <<: *default
  database: budgie_prod
  url: <%= ENV['DATABASE_URL'] %>
