default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PGUSER"] || "postgres" %>
  password: <%= ENV["PGPASSWORD"] || "" %>
  host: <%= ENV["PGHOST"] || "localhost" %>

development:
  <<: *default
  database: budgie

test:
  <<: *default
  database: budgie_test

production:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: budgie_prod
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
